version: "3.8"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    command: uvicorn src.user_institution_api.api.endpoints:app --host 0.0.0.0 --port 8000